### PR TITLE
Specify getPose() and getViewerPose() in terms of native origins

### PR DESCRIPTION
**Pull request by Manishearth**
Address part of point 1 in https://github.com/immersive-web/editor-collab/pull/36#pullrequestreview-229743358

I can add some more matrix math here if folks want, but for now I'll just reuse the multiply algorithm.

### CODE REVIEW

**Comment by Manishearth** [comment]
Eep, my bad. That definitely should be the effective origin.

I won't be able to update these till tomorrow though, feel free to continue reviewing assuming that I changed that

**Comment by Manishearth** [comment]
Updated

**Comment by NellWaliczek** [comment]
Is this covered by https://github.com/immersive-web/webxr/pull/589?

**Comment by Manishearth** [comment]
Do you mean https://github.com/immersive-web/webxr/pull/609 ? Looks like it!

**Comment by Manishearth** [comment]
The "valid pose" algorithm from this PR could be upstreamed though.

**Pull request closed without merging**
