### PR TITLE
Remove ability to dynamically modify originOffset

### PR DESCRIPTION
**Pull request by Manishearth**
Addresses point 3 of https://github.com/immersive-web/editor-collab/pull/36#pullrequestreview-229743358

This change actually makes it impossible to use originOffset -- maybe I misinterpreted that point?

r? @toji

### CODE REVIEW

**Comment by toji** [comment]
For that particular comment I believe Nell was referring to a change along the lines of PR 589 in the webxr repo, which makes the attribute readonly but also provides a way of setting it at reference space creation time. I've got an in-progress update to that particular PR that takes into account the current feedback that I can push soon.

**Comment by Manishearth** [comment]
Ah, cool. I'll wait for that and then reflect it here.

**Comment by Manishearth** [comment]
Updated anyway. To avoid changing too much at once I made `originOffset` an optional field on `XRReferenceSpaceOptions`, this could be changed to be more in line with https://github.com/immersive-web/webxr/pull/589 if necessary.

**Comment by NellWaliczek** [comment]
I think this can be closed in favor of the PR @toji has in the main repo https://github.com/immersive-web/webxr/pull/589

**Pull request closed without merging**
